name: montenegrin_localization
description: A Flutter localization package specifically designed for Montenegrin script (crnogorski/латиница) that provides comprehensive text translations and region-specific formatting.
version: 0.1.0+1
homepage: https://github.com/YassinNouh21/montenegrin_localization
repository: https://github.com/YassinNouh21/montenegrin_localization

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ">=0.18.0 <0.20.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ">=6.0.0 <8.0.0"

topics:
  - localization
  - internationalization
  - l10n
  - i18n
  - montenegrin